version: '3.7'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=76SPRNG19
    volumes:
      - ./db/Schema.sql:/docker-entrypoint-initdb.d/Schema.sql
      - ./data:/docker-entrypoint-initdb.d/csv
  server:
    image: 'ctabilas/api'
    build:
      dockerfile: Dockerfile
      context: '.'
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '4000:4000'
    environment:
      - PGUSER=root
      - PGHOST=postgres
      - PGDATABASE=api
      - PGPASSWORD=76SPRNG19
      - PGPORT=5432
volumes:
  qadata:
    driver: local
