version: '3.7'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=postgres
    build:
      dockerfile: ./db/Dockerfile
      context: '.'
    volumes:
      - /Users/charmainetabilas/Desktop/apiCSVs:/data
  server:
    image: 'ctabilas/api'
    build:
      dockerfile: Dockerfile
      context: '.'
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '4000:4000'
    environment:
      - PGUSER=root
      - PGHOST=postgres
      - PGDATABASE=api
      - PGPASSWORD=postgres
      - PGPORT=5432
volumes:
  qadata:
    driver: local
