version: '3.0'
services:
  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=password
    volumes:
      - ../data:/docker-entrypoint-initdb.d/csv
      - ./db/Schema.sql:/docker-entrypoint-initdb.d/schema.sql
  redis_db:
    image: redis:latest
  server:
    image: 'ctabilas/api'
    build:
      dockerfile: Dockerfile
      context: '.'
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '4000:4000'
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=api
      - PGPASSWORD=password
      - PGPORT=5432
      - redisHOST=redis_db
