version: '3.0'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=POSTGRES
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=POSTGRES
    volumes:
      - ../data:/docker-entrypoint-initdb.d/csv
      - ./db/Schema.sql:/docker-entrypoint-initdb.d/schema.sql

  server:
    image: 'ctabilas/api'
    build:
      dockerfile: Dockerfile
      context: '.'
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '4000:4000'
    environment:
      - PGUSER=POSTGRES
      - PGHOST=POSTGRES
      - PGDATABASE=api
      - PGPASSWORD=POSTGRES
      - PGPORT=5432
